### ISSUE TITLE
행정 구역 검색 코드 작성

### ISSUE THREAD

**Issue by Yoonhojoon** [Yoonhojoon/billage-backend#34]
In GitLab by @Byesol on Dec 3, 2024, 13:46

## 📄 설명
 읍면동 테이블에서 이름을 이용해 검색하는 코드를 작성한다.

## ✅ Tasks
- [x]  emd controller - search api 작성
- [x]  service 코드 작성
- [x]  emdarea 코드 리팩토링

## 📌 추가사항

**Comment by Yoonhojoon** [comment]
In GitLab by @Byesol on Dec 3, 2024, 13:46

marked the task **emd controller - search api 작성** as completed

**Comment by Yoonhojoon** [comment]
In GitLab by @Byesol on Dec 3, 2024, 13:46

marked the task **service 코드 작성** as completed

**Comment by Yoonhojoon** [comment]
In GitLab by @Byesol on Dec 3, 2024, 13:47

mentioned in commit d4978406fa93343ad78d6daa8c1564699bdcb5e9

**Comment by Yoonhojoon** [comment]
In GitLab by @Byesol on Dec 3, 2024, 13:48

mentioned in commit b51aba5f6689a71a2298e655e99ea1bf453aad75

**Comment by Yoonhojoon** [comment]
In GitLab by @Byesol on Dec 6, 2024, 10:41

mentioned in commit 6192d737282f51ad07b7ca3eb7ba823c00f12b51
